<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace("SixDemonBag.","Six.Demon.Bag.").Replace(".Sdk",""))</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
</Project>